name: Hello World on PR

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - gangothri

jobs:
  greet:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo "Hello World"
